"""add dictionary lookup persistence fields

Revision ID: a3138bd4431c
Revises: 8d587f628bd2
Create Date: 2026-09-01 19:30:48.479951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3138bd4431c'
down_revision: Union[str, Sequence[str], None] = '8d587f628bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_antonyms',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('definition_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('antonym', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['word_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'antonym', name='uq_word_antonyms_definition_id_antonym')
    )
    op.create_index(op.f('ix_word_antonyms_definition_id'), 'word_antonyms', ['definition_id'], unique=False)
    op.add_column('words', sa.Column('phonetic', sa.String(length=255), nullable=True))
    op.add_column('words', sa.Column('audio_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'audio_url')
    op.drop_column('words', 'phonetic')
    op.drop_index(op.f('ix_word_antonyms_definition_id'), table_name='word_antonyms')
    op.drop_table('word_antonyms')
    # ### end Alembic commands ###
