"""update dictionary tables

Revision ID: ed5f5ca94a0b
Revises: 85613cf65d51
Create Date: 2026-08-18 17:18:48.593306

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed5f5ca94a0b"
down_revision: Union[str, Sequence[str], None] = "85613cf65d51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "word_definitions",
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
    )
    op.create_unique_constraint(
        "uq_word_synonyms_definition_id_synonym",
        "word_synonyms",
        ["definition_id", "synonym"],
    )
    op.alter_column(
        "words",
        "language",
        existing_type=sa.String(length=16),
        server_default="en",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_word_synonyms_definition_id_synonym",
        "word_synonyms",
        type_="unique",
    )
    op.drop_column("word_definitions", "position")
    op.alter_column(
        "words",
        "language",
        existing_type=sa.String(length=16),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
