"""create dictionary tables

Revision ID: f3f4c8aaede3
Revises: e25d77cdcbf7
Create Date: 2026-08-18 14:55:32.000255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3f4c8aaede3"
down_revision: Union[str, Sequence[str], None] = "e25d77cdcbf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("provider_lookup_key", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("text", "language", name="uq_words_text_language"),
    )
    op.create_index(op.f("ix_words_text"), "words", ["text"], unique=False)
    op.create_table(
        "word_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("part_of_speech", sa.String(length=50), nullable=True),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_word_definitions_word_id"),
        "word_definitions",
        ["word_id"],
        unique=False,
    )
    op.create_table(
        "word_examples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("example", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_word_examples_word_id"), "word_examples", ["word_id"], unique=False
    )
    op.create_table(
        "word_synonyms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("synonym", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_word_synonyms_word_id"), "word_synonyms", ["word_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_word_synonyms_word_id"), table_name="word_synonyms")
    op.drop_table("word_synonyms")
    op.drop_index(op.f("ix_word_examples_word_id"), table_name="word_examples")
    op.drop_table("word_examples")
    op.drop_index(op.f("ix_word_definitions_word_id"), table_name="word_definitions")
    op.drop_table("word_definitions")
    op.drop_index(op.f("ix_words_text"), table_name="words")
    op.drop_table("words")
    # ### end Alembic commands ###
